apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app-deployment
  labels:
    app: insurance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
      - name: insurance-app
        image: skyrius6732/insurance-project:latest
        imagePullPolicy: IfNotPresent # 로컬에 없으면 가져오도록 설정
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-plain-bootstrap.kafka:9092"
        - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
          value: "http://schema-registry.kafka:8081"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.H2Dialect"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
